### ISSUE TITLE
feat(wasm): [EPIC] Wasm bindings for the perp module

### ISSUE THREAD

**Issue by Unique-Divine** [NibiruChain/nibiru#1272]
### Tests

- [x] test(wasm): Test conversions from proto to JSON marshalled response
- [x] test(wasm): Test submission of custom message that binds to `x/perp` from a smart contract.
    For example, we could use a smart contract that simply opens a position or closes one. 
- [x] test(wasm): Test inputs and outputs (JSON and protos) when passing bytes through the Nibiru bindings querier. 
- [x] test(wasm): Test a custom query of one of our modules from a smart contract. 

### Features: Messages

- [x] (perp): Bindings for `Msg.RemoveMargin`
- [x] (perp): Bindings for `Msg.AddMargin`
- [x] (perp): Bindings for `Msg.MultiLiquidate`
- [x] (perp): Bindings for `Msg.OpenPosition`
- [x] (perp): Bindings for `Msg.ClosePosition`

### Features: Queries

- [x] (perp): Bindings to query the reserves
- [x] (perp): Bindings to query all markets
- [x] (perp): Bindings to query base price
- [x] (perp): Bindings to query positions
- [x] (perp): Bindings to query a single position
- [x] (perp): Bindings to query the cumulative premium fraction
- [x] (perp): Bindings to query metrics
- [x] (perp): Bindings to query module accounts
- [x] (perp): Bindings to query params

## Related

- #1274 
- #1287

**Comment by Unique-Divine** [comment]
Completed this several months ago
