### ISSUE TITLE
epic: feat(perp): `SettlePosition` tx

### ISSUE THREAD

**Issue by k-yang** [NibiruChain/nibiru#1474]
## Context

When markets are stopped, users need a way to settle their position.

## 2023-08-23 

- [x] epic: Settle to uniform price 
   - [ ] feat: Settle should have its own TxMsg (with version as an arg)
   - [ ] When I query all my positions, I should see unsettled ones too.
   - [ ] (default) nibid q markets: Returns only what's open
   - [ ] p1: nibid q markets --versioned: Everything with pagination
   - [ ] err: if the market is enabled. You can only settle if the market is not enabled
   - [ ] taker fee (+ discount) on settle.
   - [ ] #1551

- [x] #1550
  - [ ] Create Market + specify version (fails if ) -> Stop previous market
    - case 0:If called , auto look at latest v, if latest v is open, error: early return / abort
    - case 1: If latest v is closed, make new market with incremented fee.  
    - case 2: If there's no last version, it's v0. (special case of case 1.
  - [ ] Both pair and versions are individual fields of the state
