### ISSUE TITLE
refactor(perp): Prefer Int over Dec

### ISSUE THREAD

**Issue by Unique-Divine** [NibiruChain/nibiru#1480]
## Context

Many types that we have as decimals could be more easily represented with `sdk.Int` types.

## Smaller PRs Breakdown

Please tag this issue. This ticket combines a bunch of smaller ones that were creating noise. 

- [ ] refactor(perp)!: Change AMM reserves to Int 
- [ ] refactor(perp)!: margin as Int 
- [ ] refactor(perp)!: notional as Int 
- [ ] refactor(perp)!: size as Int
- [ ] refactor(perp)!: express pnl as Int 
- [ ] refactor(perp)!: fees as Int 
- [ ] #1481

--- 

## What should be a sdk.Dec?

- Cumulative Funding 
- Leverage

**Comment by Unique-Divine** [comment]
De-prioritized
