### ISSUE TITLE
feat(perp): Query for all positions in state

### ISSUE THREAD

**Issue by Unique-Divine** [NibiruChain/nibiru#1557]
Thoughts on making this take a pair argument to be less heavy? You could imagine a case where we have 50+ pairs and this query becomes massive

_Originally posted by @Unique-Divine in https://github.com/NibiruChain/nibiru/issues/1059#issuecomment-1312768228_

## Tasks

- [ ] Implement gRPC query
- [ ] Test gRPC query
- [ ] Add command to the CLI

## Related

- #1558
