### ISSUE TITLE
feat(wasm): Create a Rust package to call module TxMsgs with `CosmosMsg::StargateMsg`

### ISSUE THREAD

**Issue by Unique-Divine** [NibiruChain/nibiru#1580]
Tracking issue for migrating wasm bindings to use `CosmosMsg::StargateMsg`

## Higher Prio
- [ ] Generate Rust proto types
- [ ] Create Stargate messages for `x/tokenfactory`  (with tests)
- [ ] Create Stargate queries for `x/oracle` (with tests)

## Nice to Have
- [ ] Create Stargate messages for `x/perp` 
- [ ] Create Stargate messages for `x/spot`

**Comment by Unique-Divine** [comment]
Update: The framework for completing this ticket is implemented inside the `nibiru_std::proto` crate with the `NibiruStargateMsg` and `NibiruStargateQuery` traits. Several trait implementations have already been added in files like [proto/type_url_nibiru.rs](https://github.com/NibiruChain/cw-nibiru/blob/becc614b5a1b51f3da2e1646a3f26be91340627c/nibiru-std/src/proto/type_url_nibiru.rs).

To complete the remainder of this task, `impl` blocks for `Prost::Name` need to be added for the above checklist, which is relatively straightforward.
