### ISSUE TITLE
epic(wasm): Removal of CosmosMsg::Custom bindings in favor of MsgServer + CosmosMsg::StargateMsg

### ISSUE THREAD

**Issue by jgimeno** [NibiruChain/nibiru#1642]
(Update 2023-12) Reopening with more accurate description

- [x] Create admin method for oracle ChangeOracleParams | #1752 
- [x] Create admin method for perp WithdrawFromPerpFund | #1734 
- [x] Create admin method for perp SetMarketEnabled (could be called CloseMarket instead)
- [x] Create admin method for perp CreateMarket
- [x] Complete new impl of `core-controller` smart contract in NibiruChain/cw-nibiru after the new methods become available. 
- Related: https://github.com/NibiruChain/cw-nibiru/issues/103

**Comment by Unique-Divine** [comment]
It's a convention taking after the [bindings used by Terra](https://github.com/terra-money/terra-cosmwasm/blob/main/packages/terra-cosmwasm/src/msg.rs#L10).

**Comment by Unique-Divine** [comment]
Reopening with more accurate description

**Comment by Unique-Divine** [comment]
cc @jgimeno , if you'd like to work on this issue as well, you could do add `SetMarketEnabled` or `CreateMarket` to the x/perp MsgServer
