### ISSUE TITLE
[epic] register simulation functions for each module

### ISSUE THREAD

**Issue by k-yang** [NibiruChain/nibiru#1738]
- [ ] Register x/epochs simulations
- [ ] Register x/devgas simulations
- [ ] Register x/inflation simulations
- [ ] Register x/oracle simulations
