### ISSUE TITLE
epic(evm): Nibiru EVM tracking ticket

### ISSUE THREAD

**Issue by Unique-Divine** [NibiruChain/nibiru#1836]
## Abstract / Purpose

EVM compatibility to support dApps in Solidity, parse EVM bytecode, and implement the Ethereum protocol's JSON-RPC specification. 

<details open>
  <summary>[Click to Expand Roadmap Graphic]</summary>
  
  ![image](https://github.com/NibiruChain/nibiru/assets/51418232/d8eade8f-edd0-4d0a-9725-c8b67b6a29c9)
</details>

---

## 1 | EVM contracts

- [x] Implement Ethereum protobufs and types | #1837 
- [x] Eth RPC impl and tests
- [x] #1875
- [x] #1876
- [x] #1877
- [x] #1878
- [x] #1879
- [x] Cryptography additions for ethsecp256k1
- [x] #1880
- [x] #1881
- [x] #1902
- [x] #1975 

## 2 | Fungible Token Extension

- [x] #1898
- [x] #1882
- [x] #1952 

## 3 | Quality Improvements & Audit Readiness

- [x] #1919 
- [x] #1920 
- [x] #1915 
- [x] #1916
- [x] #1964 

## 4 | Precompile Items for Oct 10, 2024 Audit

- [x] #2048 | @Unique-Divine 
- [x] #2049 
- [x] #2051 

## 4 | Outside Scope / Non-essentials 

These tickets aren't necessarily bad to work on, but they are non-essentials for right now. 

- #1921
- #1857
- #1860

**Comment by cgilbe27** [comment]
Related

https://github.com/NibiruChain/nibiru/issues/2026

**Comment by Unique-Divine** [comment]
All of the boxes are checked. Closing as completed
