### ISSUE TITLE
epic(evm): fungible tokens: Coin to ERC20 and ERC20 to Coin

### ISSUE THREAD

**Issue by Unique-Divine** [NibiruChain/nibiru#1898]
## Objective 

Extend the x/evm module to enable the creation of coins (native fungible tokens) from ERC20 contract tokens on the Nibiru EVM, and to create ERC20 tokens from coins.

## Specification

[Specification Backlink (Notion)](https://www.notion.so/nibiru/FunToken-Fungible-Token-Standards-and-EVM-06e07b86d9e2446594b4f693cbeb1110?pvs=4)

## Tickets

See [User Stories (Spec)](https://www.notion.so/nibiru/FunToken-Fungible-Token-Standards-and-EVM-06e07b86d9e2446594b4f693cbeb1110?pvs=4#d42b1c73ce84417cb7156101c9c030a2)

- [x] #1882
- [x] #1944
- [x] #1943
- [x] #1942: Functionality to create the FunToken mapping for a bank coin, producing a corresponding ERC20 contract.
- [x] #1941: Functionality to create the FunToken mapping for an ERC20 token contract, producing a bank coin by storing its metadata in state.
- [x] #1940
- [x] [WIP] Describe and create tickets for [frontend UI/UX changes](https://www.notion.so/nibiru/FunToken-Fungible-Token-Standards-and-EVM-06e07b86d9e2446594b4f693cbeb1110?pvs=4#b4a3982976c24a089d7d299278f51959) to fit into sprints. For example, MetaMask setup

--- 

This ticket is part of #1836

**Comment by Unique-Divine** [comment]
Update: Assigned "homework" to the group to deliberate on designs and draft and initial proposal by June 14, 2024.  cc @onikonychev @k-yang

**Comment by cgilbe27** [comment]
https://github.com/NibiruChain/web-app/issues/1077
