### ISSUE TITLE
ci, test: Continuous Integration with GitHub Actions

### ISSUE THREAD

**Issue by VimDiesel-Cosmos** [NibiruChain/nibiru#19]
We need to setup continuous integration testing to:
- [x] Verify the `make build` works properly. -> PR [test: add 'make build' to CI workflow](https://github.com/MatrixDao/matrix/pull/36)
- [x] (Deprecated) Verify that `make proto-gen` runs properly. 
- [x] All `x/...` tests run with `go test ./...` -> [feat/add-gh-test-workflow](https://github.com/MatrixDao/matrix/pull/24#partial-pull-merging)
