### ISSUE TITLE
docs(stablecoin): [EPIC] liquidity ratio, collateral ratio

### ISSUE THREAD

**Issue by Unique-Divine** [NibiruChain/nibiru#200]
- [x] docs: Add to notion
- [x] docs: Add to spec
- [x] docs: Add to function and type definitions

**Comment by Unique-Divine** [comment]
Already live on the public docs
