### ISSUE TITLE
test(eth-rpc-backend): Remove mocked calls in favor of real transactions and blocks

### ISSUE THREAD

**Issue by Unique-Divine** [NibiruChain/nibiru#2033]
This will make it easier to update the `EVMIndexer` and RPC APIs without causing breaking production

- [x] Restore account_info_test.go with `testnetwork` #2042
- [x] Restore backend_suite_test.go with `testnetwork` - already covered
- [x] Restore blocks_test.go with `testnetwork` #2042
- [x] Restore call_tx_test.go with `testnetwork`  #2042
- [x] Restore chain_info_test.go with `testnetwork` #2042
- [x] Restore evm_query_client_test.go with `testnetwork` #2042
- [x] Restore filters_test.go with `testnetwork` #2042
- [x] Restore node_info_test.go with `testnetwork` #2042
- [x] Restore sign_tx_test.go with `testnetwork` (#2042 removed `sign_tx` api entirely as deprecated and unused)
- [x] Restore tracing_test.go with `testnetwork` (@onikonychev  #2038 )
- [x] Restore tx_info_test.go with `testnetwork` (@onikonychev  #2038 )
- [x] Restore utils_test.go with `testnetwork` (#2042 there is a todo waiting for Log events properly implmented)

**Comment by Unique-Divine** [comment]
- Implementation completed by https://github.com/NibiruChain/nibiru/pull/2045
