### ISSUE TITLE
chore: [EPIC] Add Nibiru to the Cosmos 'chain-registry'

### ISSUE THREAD

**Issue by Unique-Divine** [NibiruChain/nibiru#536]
### Overview

We'll need a setup similar to Evmos, Terra, etc. on [[cosmos/chain-registry repo]](https://github.com/cosmos/chain-registry).

Chain schema: [[cosmos/chain-registry/chain.schema.json]][chain-schema]

### Tasks (in-progress @Unique-Divine)

- [ ] Create nibiru/chain.json based on the [chain schema][chain-schema]

- [ ] Create nibiru/assetlist.json using [these instructions](https://github.com/cosmos/chain-registry#assetlists).
  - [ ] Get high-quality png for the NIBI token
  - [ ] Get matching svg for the NIBI token
  - [ ] Native token (NIBI) added with denom, exponent, base, display, symbol, and logo URIs. 

- [ ] IBC Data registration (TODO)

[chain-schema]: https://github.com/cosmos/chain-registry/blob/master/chain.schema.json
