### ISSUE TITLE
docs(vpool): [EPIC] module specification

### ISSUE THREAD

**Issue by Unique-Divine** [NibiruChain/nibiru#568]
- [ ] docs(vpool): `XX_client.md` spec that describes that CLI commands, gRPC endpoints, and REST endpoints
- [ ] docs(vpool): `XX_state.md` spec that describes data structures to be marshalled into the store and their keys
- [ ] docs(vpool): `XX_events.md` spec
- [ ] docs(vpool): `XX_concepts.md` specification that describes specialized concepts and definitions 
- [ ] docs(vpool): `README.md` that provides an overview of the module, summarizes each major section, and hyperlinks to them
