### ISSUE TITLE
docs(perp): [EPIC] module specification 

### ISSUE THREAD

**Issue by Unique-Divine** [NibiruChain/nibiru#572]
### Epic Summary 

- [x] docs(perp): `XX_client.md` spec that describes that CLI commands, gRPC endpoints, and REST endpoints
- [x] #573
- [x] #574
- [x] docs(perp): `XX_concepts.md` specification that describes specialized concepts and definitions 
- [x] docs(perp): `README.md` that provides an overview of the module, summarizes each major section, and hyperlinks to them 

### Related: 

- #425
