### ISSUE TITLE
refactor(proto): proto files consistency for Testnet V2 modules.

### ISSUE THREAD

**Issue by AgentSmithMatrix** [NibiruChain/nibiru#923]
### Summary 

Same as https://github.com/NibiruChain/nibiru/issues/523 but for the modules that are included in testnet V2.

> Let's follow the [cosmos-sdk best practices](https://docs.cosmos.network/master/building-modules/structure.html#structure).

### Refactor protos to follow certain conventions:

| File | Description | 
| --- | --- | 
| `query.proto` | contains only query definitions for the query RPC service. | 
| `tx.proto` | contains only Msg definitions for the messages.  |
| `state.proto` | should contain everything that is saved into state (dependencies excluded). |
| `module_name.proto` | should contain every type that is shared across the other proto files of the module (query,tx...), events etc. |

### Tasks

- [ ] refactor!(proto): `x/stablecoin` module - follow proto conventions
- [ ] refactor!(proto): `x/dex` module - follow proto conventions
- [ ] refactor!(proto): Make x/stablecoin follow proto conventions

**Comment by Unique-Divine** [comment]
It seems we evolved toward using this convention and completed the ticket. Here's the current tree (12ee6806f6c718cd22239f95839f3ef8bda7780b): 

```
 proto/nibiru
├── devgas
│  └── v1
│     ├── devgas.proto
│     ├── event.proto
│     ├── genesis.proto
│     ├── query.proto
│     └── tx.proto
├── epochs
│  └── v1
│     ├── event.proto
│     ├── genesis.proto
│     ├── query.proto
│     └── state.proto
├── genmsg
│  └── v1
│     └── genmsg.proto
├── inflation
│  └── v1
│     ├── event.proto
│     ├── genesis.proto
│     ├── inflation.proto
│     └── query.proto
├── oracle
│  └── v1
│     ├── event.proto
│     ├── genesis.proto
│     ├── oracle.proto
│     ├── query.proto
│     ├── state.proto
│     └── tx.proto
├── perp
│  └── v2
│     ├── event.proto
│     ├── genesis.proto
│     ├── query.proto
│     ├── state.proto
│     └── tx.proto
├── spot
│  └── v1
│     ├── event.proto
│     ├── genesis.proto
│     ├── params.proto
│     ├── pool.proto
│     ├── query.proto
│     └── tx.proto
├── sudo
│  └── v1
│     ├── event.proto
│     ├── query.proto
│     ├── state.proto
│     └── tx.proto
└── tokenfactory
   └── v1
      ├── event.proto
      ├── query.proto
      ├── state.proto
      └── tx.proto
```
